spring:
#Spring cloud Feign client test settings   
   cloud:
      openfeign:
         client:
            config:
               userClient:
                  url: http://db-users:8083
                  connectTimeout: 5000
                  readTimeout: 5000
                  loggerLevel: full
                  authentication:
                     username: ConnectionProdClient
                     password: connectionProdClient

#Redis config settings  
   data:
      redis:
         host: redis
         port: 6379
   
#Spring Security settings for token and registration and authentication url's
   security:
      token:
# JWT token time living in seconds
         lifeTime: 2400
         secretKey: STRAIGHT_TO_URAN
      url:
         authenticationURL: /login
         registrationURL: /signup

#Aspect settings for using controller logging and cache mechanism
aspect:
# Controller layer request and response logging controllerLogging: enable | disable
   controllerLogging: disable
# Settings for cache: enable: true | false, type: redis | custom 
# Also settings for custom caching: algorithm: lru | lfu and cache size
   cache:
      enable: true
      type: redis
      custom:
         algorithm: lru
         size: 10

connection:
   db:
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://db-news:5432/news?charSet=utf-8
      username: admin
      password: admin
      maxPoolSize: 3
      connectionTimeout: 3000
   hibernate:
      schema: none
      sessionContext: thread
      dialect: org.hibernate.dialect.PostgreSQLDialect
      showSql: true
      transactionIsolationValue: 2
